name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pushes to another repository
        uses: xvyaward/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: './'
          destination-github-username: 'ECoLab-POSTECH'
          destination-repository-name: 'OWQ'
          user-email: ckdgnsrhkspd@naver.com
          target-branch: main